version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/nature-remo-api-server"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/nature-remo-web-ui"
    schedule:
      interval: "weekly"
