// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGet1AppliancesApplianceSignalsParams creates a new Get1AppliancesApplianceSignalsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGet1AppliancesApplianceSignalsParams() *Get1AppliancesApplianceSignalsParams {
	return &Get1AppliancesApplianceSignalsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGet1AppliancesApplianceSignalsParamsWithTimeout creates a new Get1AppliancesApplianceSignalsParams object
// with the ability to set a timeout on a request.
func NewGet1AppliancesApplianceSignalsParamsWithTimeout(timeout time.Duration) *Get1AppliancesApplianceSignalsParams {
	return &Get1AppliancesApplianceSignalsParams{
		timeout: timeout,
	}
}

// NewGet1AppliancesApplianceSignalsParamsWithContext creates a new Get1AppliancesApplianceSignalsParams object
// with the ability to set a context for a request.
func NewGet1AppliancesApplianceSignalsParamsWithContext(ctx context.Context) *Get1AppliancesApplianceSignalsParams {
	return &Get1AppliancesApplianceSignalsParams{
		Context: ctx,
	}
}

// NewGet1AppliancesApplianceSignalsParamsWithHTTPClient creates a new Get1AppliancesApplianceSignalsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGet1AppliancesApplianceSignalsParamsWithHTTPClient(client *http.Client) *Get1AppliancesApplianceSignalsParams {
	return &Get1AppliancesApplianceSignalsParams{
		HTTPClient: client,
	}
}

/* Get1AppliancesApplianceSignalsParams contains all the parameters to send to the API endpoint
   for the get1 appliances appliance signals operation.

   Typically these are written to a http.Request.
*/
type Get1AppliancesApplianceSignalsParams struct {

	/* Appliance.

	   Appliance ID.
	*/
	Appliance string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get1 appliances appliance signals params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *Get1AppliancesApplianceSignalsParams) WithDefaults() *Get1AppliancesApplianceSignalsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get1 appliances appliance signals params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *Get1AppliancesApplianceSignalsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get1 appliances appliance signals params
func (o *Get1AppliancesApplianceSignalsParams) WithTimeout(timeout time.Duration) *Get1AppliancesApplianceSignalsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get1 appliances appliance signals params
func (o *Get1AppliancesApplianceSignalsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get1 appliances appliance signals params
func (o *Get1AppliancesApplianceSignalsParams) WithContext(ctx context.Context) *Get1AppliancesApplianceSignalsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get1 appliances appliance signals params
func (o *Get1AppliancesApplianceSignalsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get1 appliances appliance signals params
func (o *Get1AppliancesApplianceSignalsParams) WithHTTPClient(client *http.Client) *Get1AppliancesApplianceSignalsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get1 appliances appliance signals params
func (o *Get1AppliancesApplianceSignalsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppliance adds the appliance to the get1 appliances appliance signals params
func (o *Get1AppliancesApplianceSignalsParams) WithAppliance(appliance string) *Get1AppliancesApplianceSignalsParams {
	o.SetAppliance(appliance)
	return o
}

// SetAppliance adds the appliance to the get1 appliances appliance signals params
func (o *Get1AppliancesApplianceSignalsParams) SetAppliance(appliance string) {
	o.Appliance = appliance
}

// WriteToRequest writes these params to a swagger request
func (o *Get1AppliancesApplianceSignalsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param appliance
	if err := r.SetPathParam("appliance", o.Appliance); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
