// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGet1DevicesParams creates a new Get1DevicesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGet1DevicesParams() *Get1DevicesParams {
	return &Get1DevicesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGet1DevicesParamsWithTimeout creates a new Get1DevicesParams object
// with the ability to set a timeout on a request.
func NewGet1DevicesParamsWithTimeout(timeout time.Duration) *Get1DevicesParams {
	return &Get1DevicesParams{
		timeout: timeout,
	}
}

// NewGet1DevicesParamsWithContext creates a new Get1DevicesParams object
// with the ability to set a context for a request.
func NewGet1DevicesParamsWithContext(ctx context.Context) *Get1DevicesParams {
	return &Get1DevicesParams{
		Context: ctx,
	}
}

// NewGet1DevicesParamsWithHTTPClient creates a new Get1DevicesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGet1DevicesParamsWithHTTPClient(client *http.Client) *Get1DevicesParams {
	return &Get1DevicesParams{
		HTTPClient: client,
	}
}

/* Get1DevicesParams contains all the parameters to send to the API endpoint
   for the get1 devices operation.

   Typically these are written to a http.Request.
*/
type Get1DevicesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get1 devices params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *Get1DevicesParams) WithDefaults() *Get1DevicesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get1 devices params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *Get1DevicesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get1 devices params
func (o *Get1DevicesParams) WithTimeout(timeout time.Duration) *Get1DevicesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get1 devices params
func (o *Get1DevicesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get1 devices params
func (o *Get1DevicesParams) WithContext(ctx context.Context) *Get1DevicesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get1 devices params
func (o *Get1DevicesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get1 devices params
func (o *Get1DevicesParams) WithHTTPClient(client *http.Client) *Get1DevicesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get1 devices params
func (o *Get1DevicesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *Get1DevicesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
