// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPost1AppliancesApplianceSignalOrdersParams creates a new Post1AppliancesApplianceSignalOrdersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPost1AppliancesApplianceSignalOrdersParams() *Post1AppliancesApplianceSignalOrdersParams {
	return &Post1AppliancesApplianceSignalOrdersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPost1AppliancesApplianceSignalOrdersParamsWithTimeout creates a new Post1AppliancesApplianceSignalOrdersParams object
// with the ability to set a timeout on a request.
func NewPost1AppliancesApplianceSignalOrdersParamsWithTimeout(timeout time.Duration) *Post1AppliancesApplianceSignalOrdersParams {
	return &Post1AppliancesApplianceSignalOrdersParams{
		timeout: timeout,
	}
}

// NewPost1AppliancesApplianceSignalOrdersParamsWithContext creates a new Post1AppliancesApplianceSignalOrdersParams object
// with the ability to set a context for a request.
func NewPost1AppliancesApplianceSignalOrdersParamsWithContext(ctx context.Context) *Post1AppliancesApplianceSignalOrdersParams {
	return &Post1AppliancesApplianceSignalOrdersParams{
		Context: ctx,
	}
}

// NewPost1AppliancesApplianceSignalOrdersParamsWithHTTPClient creates a new Post1AppliancesApplianceSignalOrdersParams object
// with the ability to set a custom HTTPClient for a request.
func NewPost1AppliancesApplianceSignalOrdersParamsWithHTTPClient(client *http.Client) *Post1AppliancesApplianceSignalOrdersParams {
	return &Post1AppliancesApplianceSignalOrdersParams{
		HTTPClient: client,
	}
}

/* Post1AppliancesApplianceSignalOrdersParams contains all the parameters to send to the API endpoint
   for the post1 appliances appliance signal orders operation.

   Typically these are written to a http.Request.
*/
type Post1AppliancesApplianceSignalOrdersParams struct {

	/* Appliance.

	   Appliance ID.
	*/
	Appliance string

	/* Signals.

	   List of all signals' IDs comma separated
	*/
	Signals string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post1 appliances appliance signal orders params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *Post1AppliancesApplianceSignalOrdersParams) WithDefaults() *Post1AppliancesApplianceSignalOrdersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post1 appliances appliance signal orders params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *Post1AppliancesApplianceSignalOrdersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post1 appliances appliance signal orders params
func (o *Post1AppliancesApplianceSignalOrdersParams) WithTimeout(timeout time.Duration) *Post1AppliancesApplianceSignalOrdersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post1 appliances appliance signal orders params
func (o *Post1AppliancesApplianceSignalOrdersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post1 appliances appliance signal orders params
func (o *Post1AppliancesApplianceSignalOrdersParams) WithContext(ctx context.Context) *Post1AppliancesApplianceSignalOrdersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post1 appliances appliance signal orders params
func (o *Post1AppliancesApplianceSignalOrdersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post1 appliances appliance signal orders params
func (o *Post1AppliancesApplianceSignalOrdersParams) WithHTTPClient(client *http.Client) *Post1AppliancesApplianceSignalOrdersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post1 appliances appliance signal orders params
func (o *Post1AppliancesApplianceSignalOrdersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppliance adds the appliance to the post1 appliances appliance signal orders params
func (o *Post1AppliancesApplianceSignalOrdersParams) WithAppliance(appliance string) *Post1AppliancesApplianceSignalOrdersParams {
	o.SetAppliance(appliance)
	return o
}

// SetAppliance adds the appliance to the post1 appliances appliance signal orders params
func (o *Post1AppliancesApplianceSignalOrdersParams) SetAppliance(appliance string) {
	o.Appliance = appliance
}

// WithSignals adds the signals to the post1 appliances appliance signal orders params
func (o *Post1AppliancesApplianceSignalOrdersParams) WithSignals(signals string) *Post1AppliancesApplianceSignalOrdersParams {
	o.SetSignals(signals)
	return o
}

// SetSignals adds the signals to the post1 appliances appliance signal orders params
func (o *Post1AppliancesApplianceSignalOrdersParams) SetSignals(signals string) {
	o.Signals = signals
}

// WriteToRequest writes these params to a swagger request
func (o *Post1AppliancesApplianceSignalOrdersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param appliance
	if err := r.SetPathParam("appliance", o.Appliance); err != nil {
		return err
	}

	// form param signals
	frSignals := o.Signals
	fSignals := frSignals
	if fSignals != "" {
		if err := r.SetFormParam("signals", fSignals); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
