// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPost1AppliancesApplianceSignalsParams creates a new Post1AppliancesApplianceSignalsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPost1AppliancesApplianceSignalsParams() *Post1AppliancesApplianceSignalsParams {
	return &Post1AppliancesApplianceSignalsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPost1AppliancesApplianceSignalsParamsWithTimeout creates a new Post1AppliancesApplianceSignalsParams object
// with the ability to set a timeout on a request.
func NewPost1AppliancesApplianceSignalsParamsWithTimeout(timeout time.Duration) *Post1AppliancesApplianceSignalsParams {
	return &Post1AppliancesApplianceSignalsParams{
		timeout: timeout,
	}
}

// NewPost1AppliancesApplianceSignalsParamsWithContext creates a new Post1AppliancesApplianceSignalsParams object
// with the ability to set a context for a request.
func NewPost1AppliancesApplianceSignalsParamsWithContext(ctx context.Context) *Post1AppliancesApplianceSignalsParams {
	return &Post1AppliancesApplianceSignalsParams{
		Context: ctx,
	}
}

// NewPost1AppliancesApplianceSignalsParamsWithHTTPClient creates a new Post1AppliancesApplianceSignalsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPost1AppliancesApplianceSignalsParamsWithHTTPClient(client *http.Client) *Post1AppliancesApplianceSignalsParams {
	return &Post1AppliancesApplianceSignalsParams{
		HTTPClient: client,
	}
}

/* Post1AppliancesApplianceSignalsParams contains all the parameters to send to the API endpoint
   for the post1 appliances appliance signals operation.

   Typically these are written to a http.Request.
*/
type Post1AppliancesApplianceSignalsParams struct {

	/* Appliance.

	   Appliance ID.
	*/
	Appliance string

	/* Image.

	   Basename of the image file included in the app. Ex: "ico_io"

	*/
	Image string

	/* Message.

	   JSON serialized object describing infrared signals. Includes "data", "freq" and "format" keys.
	*/
	Message string

	/* Name.

	   Signal name
	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post1 appliances appliance signals params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *Post1AppliancesApplianceSignalsParams) WithDefaults() *Post1AppliancesApplianceSignalsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post1 appliances appliance signals params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *Post1AppliancesApplianceSignalsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post1 appliances appliance signals params
func (o *Post1AppliancesApplianceSignalsParams) WithTimeout(timeout time.Duration) *Post1AppliancesApplianceSignalsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post1 appliances appliance signals params
func (o *Post1AppliancesApplianceSignalsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post1 appliances appliance signals params
func (o *Post1AppliancesApplianceSignalsParams) WithContext(ctx context.Context) *Post1AppliancesApplianceSignalsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post1 appliances appliance signals params
func (o *Post1AppliancesApplianceSignalsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post1 appliances appliance signals params
func (o *Post1AppliancesApplianceSignalsParams) WithHTTPClient(client *http.Client) *Post1AppliancesApplianceSignalsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post1 appliances appliance signals params
func (o *Post1AppliancesApplianceSignalsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppliance adds the appliance to the post1 appliances appliance signals params
func (o *Post1AppliancesApplianceSignalsParams) WithAppliance(appliance string) *Post1AppliancesApplianceSignalsParams {
	o.SetAppliance(appliance)
	return o
}

// SetAppliance adds the appliance to the post1 appliances appliance signals params
func (o *Post1AppliancesApplianceSignalsParams) SetAppliance(appliance string) {
	o.Appliance = appliance
}

// WithImage adds the image to the post1 appliances appliance signals params
func (o *Post1AppliancesApplianceSignalsParams) WithImage(image string) *Post1AppliancesApplianceSignalsParams {
	o.SetImage(image)
	return o
}

// SetImage adds the image to the post1 appliances appliance signals params
func (o *Post1AppliancesApplianceSignalsParams) SetImage(image string) {
	o.Image = image
}

// WithMessage adds the message to the post1 appliances appliance signals params
func (o *Post1AppliancesApplianceSignalsParams) WithMessage(message string) *Post1AppliancesApplianceSignalsParams {
	o.SetMessage(message)
	return o
}

// SetMessage adds the message to the post1 appliances appliance signals params
func (o *Post1AppliancesApplianceSignalsParams) SetMessage(message string) {
	o.Message = message
}

// WithName adds the name to the post1 appliances appliance signals params
func (o *Post1AppliancesApplianceSignalsParams) WithName(name string) *Post1AppliancesApplianceSignalsParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the post1 appliances appliance signals params
func (o *Post1AppliancesApplianceSignalsParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *Post1AppliancesApplianceSignalsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param appliance
	if err := r.SetPathParam("appliance", o.Appliance); err != nil {
		return err
	}

	// form param image
	frImage := o.Image
	fImage := frImage
	if fImage != "" {
		if err := r.SetFormParam("image", fImage); err != nil {
			return err
		}
	}

	// form param message
	frMessage := o.Message
	fMessage := frMessage
	if fMessage != "" {
		if err := r.SetFormParam("message", fMessage); err != nil {
			return err
		}
	}

	// form param name
	frName := o.Name
	fName := frName
	if fName != "" {
		if err := r.SetFormParam("name", fName); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
