// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// Post1SignalsSignalReader is a Reader for the Post1SignalsSignal structure.
type Post1SignalsSignalReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Post1SignalsSignalReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPost1SignalsSignalOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPost1SignalsSignalOK creates a Post1SignalsSignalOK with default headers values
func NewPost1SignalsSignalOK() *Post1SignalsSignalOK {
	return &Post1SignalsSignalOK{}
}

/* Post1SignalsSignalOK describes a response with status code 200, with default header values.

Updated infrared signal
*/
type Post1SignalsSignalOK struct {
}

// IsSuccess returns true when this post1 signals signal o k response has a 2xx status code
func (o *Post1SignalsSignalOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post1 signals signal o k response has a 3xx status code
func (o *Post1SignalsSignalOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post1 signals signal o k response has a 4xx status code
func (o *Post1SignalsSignalOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post1 signals signal o k response has a 5xx status code
func (o *Post1SignalsSignalOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post1 signals signal o k response a status code equal to that given
func (o *Post1SignalsSignalOK) IsCode(code int) bool {
	return code == 200
}

func (o *Post1SignalsSignalOK) Error() string {
	return fmt.Sprintf("[POST /1/signals/{signal}][%d] post1SignalsSignalOK ", 200)
}

func (o *Post1SignalsSignalOK) String() string {
	return fmt.Sprintf("[POST /1/signals/{signal}][%d] post1SignalsSignalOK ", 200)
}

func (o *Post1SignalsSignalOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
