// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPost1UsersMeParams creates a new Post1UsersMeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPost1UsersMeParams() *Post1UsersMeParams {
	return &Post1UsersMeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPost1UsersMeParamsWithTimeout creates a new Post1UsersMeParams object
// with the ability to set a timeout on a request.
func NewPost1UsersMeParamsWithTimeout(timeout time.Duration) *Post1UsersMeParams {
	return &Post1UsersMeParams{
		timeout: timeout,
	}
}

// NewPost1UsersMeParamsWithContext creates a new Post1UsersMeParams object
// with the ability to set a context for a request.
func NewPost1UsersMeParamsWithContext(ctx context.Context) *Post1UsersMeParams {
	return &Post1UsersMeParams{
		Context: ctx,
	}
}

// NewPost1UsersMeParamsWithHTTPClient creates a new Post1UsersMeParams object
// with the ability to set a custom HTTPClient for a request.
func NewPost1UsersMeParamsWithHTTPClient(client *http.Client) *Post1UsersMeParams {
	return &Post1UsersMeParams{
		HTTPClient: client,
	}
}

/* Post1UsersMeParams contains all the parameters to send to the API endpoint
   for the post1 users me operation.

   Typically these are written to a http.Request.
*/
type Post1UsersMeParams struct {

	/* Nickname.

	   User's nickname.

	*/
	Nickname string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post1 users me params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *Post1UsersMeParams) WithDefaults() *Post1UsersMeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post1 users me params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *Post1UsersMeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post1 users me params
func (o *Post1UsersMeParams) WithTimeout(timeout time.Duration) *Post1UsersMeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post1 users me params
func (o *Post1UsersMeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post1 users me params
func (o *Post1UsersMeParams) WithContext(ctx context.Context) *Post1UsersMeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post1 users me params
func (o *Post1UsersMeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post1 users me params
func (o *Post1UsersMeParams) WithHTTPClient(client *http.Client) *Post1UsersMeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post1 users me params
func (o *Post1UsersMeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNickname adds the nickname to the post1 users me params
func (o *Post1UsersMeParams) WithNickname(nickname string) *Post1UsersMeParams {
	o.SetNickname(nickname)
	return o
}

// SetNickname adds the nickname to the post1 users me params
func (o *Post1UsersMeParams) SetNickname(nickname string) {
	o.Nickname = nickname
}

// WriteToRequest writes these params to a swagger request
func (o *Post1UsersMeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// form param nickname
	frNickname := o.Nickname
	fNickname := frNickname
	if fNickname != "" {
		if err := r.SetFormParam("nickname", fNickname); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
