// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPost1SignalsSignalSendParams creates a new Post1SignalsSignalSendParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPost1SignalsSignalSendParams() *Post1SignalsSignalSendParams {
	return &Post1SignalsSignalSendParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPost1SignalsSignalSendParamsWithTimeout creates a new Post1SignalsSignalSendParams object
// with the ability to set a timeout on a request.
func NewPost1SignalsSignalSendParamsWithTimeout(timeout time.Duration) *Post1SignalsSignalSendParams {
	return &Post1SignalsSignalSendParams{
		timeout: timeout,
	}
}

// NewPost1SignalsSignalSendParamsWithContext creates a new Post1SignalsSignalSendParams object
// with the ability to set a context for a request.
func NewPost1SignalsSignalSendParamsWithContext(ctx context.Context) *Post1SignalsSignalSendParams {
	return &Post1SignalsSignalSendParams{
		Context: ctx,
	}
}

// NewPost1SignalsSignalSendParamsWithHTTPClient creates a new Post1SignalsSignalSendParams object
// with the ability to set a custom HTTPClient for a request.
func NewPost1SignalsSignalSendParamsWithHTTPClient(client *http.Client) *Post1SignalsSignalSendParams {
	return &Post1SignalsSignalSendParams{
		HTTPClient: client,
	}
}

/* Post1SignalsSignalSendParams contains all the parameters to send to the API endpoint
   for the post1 signals signal send operation.

   Typically these are written to a http.Request.
*/
type Post1SignalsSignalSendParams struct {

	/* Signal.

	   Signal ID.
	*/
	Signal string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post1 signals signal send params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *Post1SignalsSignalSendParams) WithDefaults() *Post1SignalsSignalSendParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post1 signals signal send params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *Post1SignalsSignalSendParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post1 signals signal send params
func (o *Post1SignalsSignalSendParams) WithTimeout(timeout time.Duration) *Post1SignalsSignalSendParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post1 signals signal send params
func (o *Post1SignalsSignalSendParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post1 signals signal send params
func (o *Post1SignalsSignalSendParams) WithContext(ctx context.Context) *Post1SignalsSignalSendParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post1 signals signal send params
func (o *Post1SignalsSignalSendParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post1 signals signal send params
func (o *Post1SignalsSignalSendParams) WithHTTPClient(client *http.Client) *Post1SignalsSignalSendParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post1 signals signal send params
func (o *Post1SignalsSignalSendParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSignal adds the signal to the post1 signals signal send params
func (o *Post1SignalsSignalSendParams) WithSignal(signal string) *Post1SignalsSignalSendParams {
	o.SetSignal(signal)
	return o
}

// SetSignal adds the signal to the post1 signals signal send params
func (o *Post1SignalsSignalSendParams) SetSignal(signal string) {
	o.Signal = signal
}

// WriteToRequest writes these params to a swagger request
func (o *Post1SignalsSignalSendParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param signal
	if err := r.SetPathParam("signal", o.Signal); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
