// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// Post1SignalsSignalDeleteReader is a Reader for the Post1SignalsSignalDelete structure.
type Post1SignalsSignalDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Post1SignalsSignalDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPost1SignalsSignalDeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPost1SignalsSignalDeleteOK creates a Post1SignalsSignalDeleteOK with default headers values
func NewPost1SignalsSignalDeleteOK() *Post1SignalsSignalDeleteOK {
	return &Post1SignalsSignalDeleteOK{}
}

/* Post1SignalsSignalDeleteOK describes a response with status code 200, with default header values.

Deleted a signal
*/
type Post1SignalsSignalDeleteOK struct {
}

// IsSuccess returns true when this post1 signals signal delete o k response has a 2xx status code
func (o *Post1SignalsSignalDeleteOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post1 signals signal delete o k response has a 3xx status code
func (o *Post1SignalsSignalDeleteOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post1 signals signal delete o k response has a 4xx status code
func (o *Post1SignalsSignalDeleteOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post1 signals signal delete o k response has a 5xx status code
func (o *Post1SignalsSignalDeleteOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post1 signals signal delete o k response a status code equal to that given
func (o *Post1SignalsSignalDeleteOK) IsCode(code int) bool {
	return code == 200
}

func (o *Post1SignalsSignalDeleteOK) Error() string {
	return fmt.Sprintf("[POST /1/signals/{signal}/delete][%d] post1SignalsSignalDeleteOK ", 200)
}

func (o *Post1SignalsSignalDeleteOK) String() string {
	return fmt.Sprintf("[POST /1/signals/{signal}/delete][%d] post1SignalsSignalDeleteOK ", 200)
}

func (o *Post1SignalsSignalDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
