// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// Post1AppliancesApplianceAirconSettingsReader is a Reader for the Post1AppliancesApplianceAirconSettings structure.
type Post1AppliancesApplianceAirconSettingsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Post1AppliancesApplianceAirconSettingsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPost1AppliancesApplianceAirconSettingsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPost1AppliancesApplianceAirconSettingsOK creates a Post1AppliancesApplianceAirconSettingsOK with default headers values
func NewPost1AppliancesApplianceAirconSettingsOK() *Post1AppliancesApplianceAirconSettingsOK {
	return &Post1AppliancesApplianceAirconSettingsOK{}
}

/* Post1AppliancesApplianceAirconSettingsOK describes a response with status code 200, with default header values.

Updated air conditioner settings
*/
type Post1AppliancesApplianceAirconSettingsOK struct {
}

// IsSuccess returns true when this post1 appliances appliance aircon settings o k response has a 2xx status code
func (o *Post1AppliancesApplianceAirconSettingsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post1 appliances appliance aircon settings o k response has a 3xx status code
func (o *Post1AppliancesApplianceAirconSettingsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post1 appliances appliance aircon settings o k response has a 4xx status code
func (o *Post1AppliancesApplianceAirconSettingsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post1 appliances appliance aircon settings o k response has a 5xx status code
func (o *Post1AppliancesApplianceAirconSettingsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post1 appliances appliance aircon settings o k response a status code equal to that given
func (o *Post1AppliancesApplianceAirconSettingsOK) IsCode(code int) bool {
	return code == 200
}

func (o *Post1AppliancesApplianceAirconSettingsOK) Error() string {
	return fmt.Sprintf("[POST /1/appliances/{appliance}/aircon_settings][%d] post1AppliancesApplianceAirconSettingsOK ", 200)
}

func (o *Post1AppliancesApplianceAirconSettingsOK) String() string {
	return fmt.Sprintf("[POST /1/appliances/{appliance}/aircon_settings][%d] post1AppliancesApplianceAirconSettingsOK ", 200)
}

func (o *Post1AppliancesApplianceAirconSettingsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
