// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// Post1SignalsSignalSendReader is a Reader for the Post1SignalsSignalSend structure.
type Post1SignalsSignalSendReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Post1SignalsSignalSendReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPost1SignalsSignalSendOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPost1SignalsSignalSendOK creates a Post1SignalsSignalSendOK with default headers values
func NewPost1SignalsSignalSendOK() *Post1SignalsSignalSendOK {
	return &Post1SignalsSignalSendOK{}
}

/* Post1SignalsSignalSendOK describes a response with status code 200, with default header values.

Successfully sent infrared signal
*/
type Post1SignalsSignalSendOK struct {
}

// IsSuccess returns true when this post1 signals signal send o k response has a 2xx status code
func (o *Post1SignalsSignalSendOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post1 signals signal send o k response has a 3xx status code
func (o *Post1SignalsSignalSendOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post1 signals signal send o k response has a 4xx status code
func (o *Post1SignalsSignalSendOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post1 signals signal send o k response has a 5xx status code
func (o *Post1SignalsSignalSendOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post1 signals signal send o k response a status code equal to that given
func (o *Post1SignalsSignalSendOK) IsCode(code int) bool {
	return code == 200
}

func (o *Post1SignalsSignalSendOK) Error() string {
	return fmt.Sprintf("[POST /1/signals/{signal}/send][%d] post1SignalsSignalSendOK ", 200)
}

func (o *Post1SignalsSignalSendOK) String() string {
	return fmt.Sprintf("[POST /1/signals/{signal}/send][%d] post1SignalsSignalSendOK ", 200)
}

func (o *Post1SignalsSignalSendOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
