// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/xruins/NatureRemoWebUI/nature-remo-api-server/pkg/remo/models"
)

// Post1DetectapplianceReader is a Reader for the Post1Detectappliance structure.
type Post1DetectapplianceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Post1DetectapplianceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPost1DetectapplianceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPost1DetectapplianceOK creates a Post1DetectapplianceOK with default headers values
func NewPost1DetectapplianceOK() *Post1DetectapplianceOK {
	return &Post1DetectapplianceOK{}
}

/* Post1DetectapplianceOK describes a response with status code 200, with default header values.

List of air conditioner model and settings. Best match comes first.
*/
type Post1DetectapplianceOK struct {
	Payload []*models.ApplianceModelAndParam
}

// IsSuccess returns true when this post1 detectappliance o k response has a 2xx status code
func (o *Post1DetectapplianceOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post1 detectappliance o k response has a 3xx status code
func (o *Post1DetectapplianceOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post1 detectappliance o k response has a 4xx status code
func (o *Post1DetectapplianceOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post1 detectappliance o k response has a 5xx status code
func (o *Post1DetectapplianceOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post1 detectappliance o k response a status code equal to that given
func (o *Post1DetectapplianceOK) IsCode(code int) bool {
	return code == 200
}

func (o *Post1DetectapplianceOK) Error() string {
	return fmt.Sprintf("[POST /1/detectappliance][%d] post1DetectapplianceOK  %+v", 200, o.Payload)
}

func (o *Post1DetectapplianceOK) String() string {
	return fmt.Sprintf("[POST /1/detectappliance][%d] post1DetectapplianceOK  %+v", 200, o.Payload)
}

func (o *Post1DetectapplianceOK) GetPayload() []*models.ApplianceModelAndParam {
	return o.Payload
}

func (o *Post1DetectapplianceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
