// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/xruins/NatureRemoWebUI/nature-remo-api-server/pkg/remo/models"
)

// Post1UsersMeReader is a Reader for the Post1UsersMe structure.
type Post1UsersMeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Post1UsersMeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPost1UsersMeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPost1UsersMeOK creates a Post1UsersMeOK with default headers values
func NewPost1UsersMeOK() *Post1UsersMeOK {
	return &Post1UsersMeOK{}
}

/* Post1UsersMeOK describes a response with status code 200, with default header values.

Successfully updated nickname
*/
type Post1UsersMeOK struct {
	Payload *models.User
}

// IsSuccess returns true when this post1 users me o k response has a 2xx status code
func (o *Post1UsersMeOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post1 users me o k response has a 3xx status code
func (o *Post1UsersMeOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post1 users me o k response has a 4xx status code
func (o *Post1UsersMeOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post1 users me o k response has a 5xx status code
func (o *Post1UsersMeOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post1 users me o k response a status code equal to that given
func (o *Post1UsersMeOK) IsCode(code int) bool {
	return code == 200
}

func (o *Post1UsersMeOK) Error() string {
	return fmt.Sprintf("[POST /1/users/me][%d] post1UsersMeOK  %+v", 200, o.Payload)
}

func (o *Post1UsersMeOK) String() string {
	return fmt.Sprintf("[POST /1/users/me][%d] post1UsersMeOK  %+v", 200, o.Payload)
}

func (o *Post1UsersMeOK) GetPayload() *models.User {
	return o.Payload
}

func (o *Post1UsersMeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.User)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
