// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPost1AppliancesApplianceLightParams creates a new Post1AppliancesApplianceLightParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPost1AppliancesApplianceLightParams() *Post1AppliancesApplianceLightParams {
	return &Post1AppliancesApplianceLightParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPost1AppliancesApplianceLightParamsWithTimeout creates a new Post1AppliancesApplianceLightParams object
// with the ability to set a timeout on a request.
func NewPost1AppliancesApplianceLightParamsWithTimeout(timeout time.Duration) *Post1AppliancesApplianceLightParams {
	return &Post1AppliancesApplianceLightParams{
		timeout: timeout,
	}
}

// NewPost1AppliancesApplianceLightParamsWithContext creates a new Post1AppliancesApplianceLightParams object
// with the ability to set a context for a request.
func NewPost1AppliancesApplianceLightParamsWithContext(ctx context.Context) *Post1AppliancesApplianceLightParams {
	return &Post1AppliancesApplianceLightParams{
		Context: ctx,
	}
}

// NewPost1AppliancesApplianceLightParamsWithHTTPClient creates a new Post1AppliancesApplianceLightParams object
// with the ability to set a custom HTTPClient for a request.
func NewPost1AppliancesApplianceLightParamsWithHTTPClient(client *http.Client) *Post1AppliancesApplianceLightParams {
	return &Post1AppliancesApplianceLightParams{
		HTTPClient: client,
	}
}

/* Post1AppliancesApplianceLightParams contains all the parameters to send to the API endpoint
   for the post1 appliances appliance light operation.

   Typically these are written to a http.Request.
*/
type Post1AppliancesApplianceLightParams struct {

	/* Appliance.

	   Appliance ID.
	*/
	Appliance string

	/* Button.

	   Button name
	*/
	Button string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post1 appliances appliance light params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *Post1AppliancesApplianceLightParams) WithDefaults() *Post1AppliancesApplianceLightParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post1 appliances appliance light params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *Post1AppliancesApplianceLightParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post1 appliances appliance light params
func (o *Post1AppliancesApplianceLightParams) WithTimeout(timeout time.Duration) *Post1AppliancesApplianceLightParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post1 appliances appliance light params
func (o *Post1AppliancesApplianceLightParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post1 appliances appliance light params
func (o *Post1AppliancesApplianceLightParams) WithContext(ctx context.Context) *Post1AppliancesApplianceLightParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post1 appliances appliance light params
func (o *Post1AppliancesApplianceLightParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post1 appliances appliance light params
func (o *Post1AppliancesApplianceLightParams) WithHTTPClient(client *http.Client) *Post1AppliancesApplianceLightParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post1 appliances appliance light params
func (o *Post1AppliancesApplianceLightParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppliance adds the appliance to the post1 appliances appliance light params
func (o *Post1AppliancesApplianceLightParams) WithAppliance(appliance string) *Post1AppliancesApplianceLightParams {
	o.SetAppliance(appliance)
	return o
}

// SetAppliance adds the appliance to the post1 appliances appliance light params
func (o *Post1AppliancesApplianceLightParams) SetAppliance(appliance string) {
	o.Appliance = appliance
}

// WithButton adds the button to the post1 appliances appliance light params
func (o *Post1AppliancesApplianceLightParams) WithButton(button string) *Post1AppliancesApplianceLightParams {
	o.SetButton(button)
	return o
}

// SetButton adds the button to the post1 appliances appliance light params
func (o *Post1AppliancesApplianceLightParams) SetButton(button string) {
	o.Button = button
}

// WriteToRequest writes these params to a swagger request
func (o *Post1AppliancesApplianceLightParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param appliance
	if err := r.SetPathParam("appliance", o.Appliance); err != nil {
		return err
	}

	// form param button
	frButton := o.Button
	fButton := frButton
	if fButton != "" {
		if err := r.SetFormParam("button", fButton); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
