// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/xruins/NatureRemoWebUI/nature-remo-api-server/pkg/remo/models"
)

// Post1AppliancesReader is a Reader for the Post1Appliances structure.
type Post1AppliancesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Post1AppliancesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPost1AppliancesCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPost1AppliancesCreated creates a Post1AppliancesCreated with default headers values
func NewPost1AppliancesCreated() *Post1AppliancesCreated {
	return &Post1AppliancesCreated{}
}

/* Post1AppliancesCreated describes a response with status code 201, with default header values.

Created an appliance
*/
type Post1AppliancesCreated struct {
	Payload *models.Appliance
}

// IsSuccess returns true when this post1 appliances created response has a 2xx status code
func (o *Post1AppliancesCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post1 appliances created response has a 3xx status code
func (o *Post1AppliancesCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post1 appliances created response has a 4xx status code
func (o *Post1AppliancesCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this post1 appliances created response has a 5xx status code
func (o *Post1AppliancesCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this post1 appliances created response a status code equal to that given
func (o *Post1AppliancesCreated) IsCode(code int) bool {
	return code == 201
}

func (o *Post1AppliancesCreated) Error() string {
	return fmt.Sprintf("[POST /1/appliances][%d] post1AppliancesCreated  %+v", 201, o.Payload)
}

func (o *Post1AppliancesCreated) String() string {
	return fmt.Sprintf("[POST /1/appliances][%d] post1AppliancesCreated  %+v", 201, o.Payload)
}

func (o *Post1AppliancesCreated) GetPayload() *models.Appliance {
	return o.Payload
}

func (o *Post1AppliancesCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Appliance)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
