// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPost1DevicesDeviceParams creates a new Post1DevicesDeviceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPost1DevicesDeviceParams() *Post1DevicesDeviceParams {
	return &Post1DevicesDeviceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPost1DevicesDeviceParamsWithTimeout creates a new Post1DevicesDeviceParams object
// with the ability to set a timeout on a request.
func NewPost1DevicesDeviceParamsWithTimeout(timeout time.Duration) *Post1DevicesDeviceParams {
	return &Post1DevicesDeviceParams{
		timeout: timeout,
	}
}

// NewPost1DevicesDeviceParamsWithContext creates a new Post1DevicesDeviceParams object
// with the ability to set a context for a request.
func NewPost1DevicesDeviceParamsWithContext(ctx context.Context) *Post1DevicesDeviceParams {
	return &Post1DevicesDeviceParams{
		Context: ctx,
	}
}

// NewPost1DevicesDeviceParamsWithHTTPClient creates a new Post1DevicesDeviceParams object
// with the ability to set a custom HTTPClient for a request.
func NewPost1DevicesDeviceParamsWithHTTPClient(client *http.Client) *Post1DevicesDeviceParams {
	return &Post1DevicesDeviceParams{
		HTTPClient: client,
	}
}

/* Post1DevicesDeviceParams contains all the parameters to send to the API endpoint
   for the post1 devices device operation.

   Typically these are written to a http.Request.
*/
type Post1DevicesDeviceParams struct {

	/* Device.

	   Device ID.
	*/
	Device string

	/* Name.

	   Signal name
	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post1 devices device params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *Post1DevicesDeviceParams) WithDefaults() *Post1DevicesDeviceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post1 devices device params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *Post1DevicesDeviceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post1 devices device params
func (o *Post1DevicesDeviceParams) WithTimeout(timeout time.Duration) *Post1DevicesDeviceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post1 devices device params
func (o *Post1DevicesDeviceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post1 devices device params
func (o *Post1DevicesDeviceParams) WithContext(ctx context.Context) *Post1DevicesDeviceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post1 devices device params
func (o *Post1DevicesDeviceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post1 devices device params
func (o *Post1DevicesDeviceParams) WithHTTPClient(client *http.Client) *Post1DevicesDeviceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post1 devices device params
func (o *Post1DevicesDeviceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDevice adds the device to the post1 devices device params
func (o *Post1DevicesDeviceParams) WithDevice(device string) *Post1DevicesDeviceParams {
	o.SetDevice(device)
	return o
}

// SetDevice adds the device to the post1 devices device params
func (o *Post1DevicesDeviceParams) SetDevice(device string) {
	o.Device = device
}

// WithName adds the name to the post1 devices device params
func (o *Post1DevicesDeviceParams) WithName(name string) *Post1DevicesDeviceParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the post1 devices device params
func (o *Post1DevicesDeviceParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *Post1DevicesDeviceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param device
	if err := r.SetPathParam("device", o.Device); err != nil {
		return err
	}

	// form param name
	frName := o.Name
	fName := frName
	if fName != "" {
		if err := r.SetFormParam("name", fName); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
