// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPost1ApplianceOrdersParams creates a new Post1ApplianceOrdersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPost1ApplianceOrdersParams() *Post1ApplianceOrdersParams {
	return &Post1ApplianceOrdersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPost1ApplianceOrdersParamsWithTimeout creates a new Post1ApplianceOrdersParams object
// with the ability to set a timeout on a request.
func NewPost1ApplianceOrdersParamsWithTimeout(timeout time.Duration) *Post1ApplianceOrdersParams {
	return &Post1ApplianceOrdersParams{
		timeout: timeout,
	}
}

// NewPost1ApplianceOrdersParamsWithContext creates a new Post1ApplianceOrdersParams object
// with the ability to set a context for a request.
func NewPost1ApplianceOrdersParamsWithContext(ctx context.Context) *Post1ApplianceOrdersParams {
	return &Post1ApplianceOrdersParams{
		Context: ctx,
	}
}

// NewPost1ApplianceOrdersParamsWithHTTPClient creates a new Post1ApplianceOrdersParams object
// with the ability to set a custom HTTPClient for a request.
func NewPost1ApplianceOrdersParamsWithHTTPClient(client *http.Client) *Post1ApplianceOrdersParams {
	return &Post1ApplianceOrdersParams{
		HTTPClient: client,
	}
}

/* Post1ApplianceOrdersParams contains all the parameters to send to the API endpoint
   for the post1 appliance orders operation.

   Typically these are written to a http.Request.
*/
type Post1ApplianceOrdersParams struct {

	/* Appliances.

	   List of all appliances' IDs comma separated
	*/
	Appliances string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post1 appliance orders params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *Post1ApplianceOrdersParams) WithDefaults() *Post1ApplianceOrdersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post1 appliance orders params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *Post1ApplianceOrdersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post1 appliance orders params
func (o *Post1ApplianceOrdersParams) WithTimeout(timeout time.Duration) *Post1ApplianceOrdersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post1 appliance orders params
func (o *Post1ApplianceOrdersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post1 appliance orders params
func (o *Post1ApplianceOrdersParams) WithContext(ctx context.Context) *Post1ApplianceOrdersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post1 appliance orders params
func (o *Post1ApplianceOrdersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post1 appliance orders params
func (o *Post1ApplianceOrdersParams) WithHTTPClient(client *http.Client) *Post1ApplianceOrdersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post1 appliance orders params
func (o *Post1ApplianceOrdersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppliances adds the appliances to the post1 appliance orders params
func (o *Post1ApplianceOrdersParams) WithAppliances(appliances string) *Post1ApplianceOrdersParams {
	o.SetAppliances(appliances)
	return o
}

// SetAppliances adds the appliances to the post1 appliance orders params
func (o *Post1ApplianceOrdersParams) SetAppliances(appliances string) {
	o.Appliances = appliances
}

// WriteToRequest writes these params to a swagger request
func (o *Post1ApplianceOrdersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// form param appliances
	frAppliances := o.Appliances
	fAppliances := frAppliances
	if fAppliances != "" {
		if err := r.SetFormParam("appliances", fAppliances); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
