// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPost1AppliancesApplianceParams creates a new Post1AppliancesApplianceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPost1AppliancesApplianceParams() *Post1AppliancesApplianceParams {
	return &Post1AppliancesApplianceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPost1AppliancesApplianceParamsWithTimeout creates a new Post1AppliancesApplianceParams object
// with the ability to set a timeout on a request.
func NewPost1AppliancesApplianceParamsWithTimeout(timeout time.Duration) *Post1AppliancesApplianceParams {
	return &Post1AppliancesApplianceParams{
		timeout: timeout,
	}
}

// NewPost1AppliancesApplianceParamsWithContext creates a new Post1AppliancesApplianceParams object
// with the ability to set a context for a request.
func NewPost1AppliancesApplianceParamsWithContext(ctx context.Context) *Post1AppliancesApplianceParams {
	return &Post1AppliancesApplianceParams{
		Context: ctx,
	}
}

// NewPost1AppliancesApplianceParamsWithHTTPClient creates a new Post1AppliancesApplianceParams object
// with the ability to set a custom HTTPClient for a request.
func NewPost1AppliancesApplianceParamsWithHTTPClient(client *http.Client) *Post1AppliancesApplianceParams {
	return &Post1AppliancesApplianceParams{
		HTTPClient: client,
	}
}

/* Post1AppliancesApplianceParams contains all the parameters to send to the API endpoint
   for the post1 appliances appliance operation.

   Typically these are written to a http.Request.
*/
type Post1AppliancesApplianceParams struct {

	/* Appliance.

	   Appliance ID.
	*/
	Appliance string

	/* Image.

	   Basename of the image file included in the app. Ex: "ico_ac_1"

	*/
	Image string

	/* Nickname.

	   Appliance name
	*/
	Nickname string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post1 appliances appliance params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *Post1AppliancesApplianceParams) WithDefaults() *Post1AppliancesApplianceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post1 appliances appliance params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *Post1AppliancesApplianceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post1 appliances appliance params
func (o *Post1AppliancesApplianceParams) WithTimeout(timeout time.Duration) *Post1AppliancesApplianceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post1 appliances appliance params
func (o *Post1AppliancesApplianceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post1 appliances appliance params
func (o *Post1AppliancesApplianceParams) WithContext(ctx context.Context) *Post1AppliancesApplianceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post1 appliances appliance params
func (o *Post1AppliancesApplianceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post1 appliances appliance params
func (o *Post1AppliancesApplianceParams) WithHTTPClient(client *http.Client) *Post1AppliancesApplianceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post1 appliances appliance params
func (o *Post1AppliancesApplianceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppliance adds the appliance to the post1 appliances appliance params
func (o *Post1AppliancesApplianceParams) WithAppliance(appliance string) *Post1AppliancesApplianceParams {
	o.SetAppliance(appliance)
	return o
}

// SetAppliance adds the appliance to the post1 appliances appliance params
func (o *Post1AppliancesApplianceParams) SetAppliance(appliance string) {
	o.Appliance = appliance
}

// WithImage adds the image to the post1 appliances appliance params
func (o *Post1AppliancesApplianceParams) WithImage(image string) *Post1AppliancesApplianceParams {
	o.SetImage(image)
	return o
}

// SetImage adds the image to the post1 appliances appliance params
func (o *Post1AppliancesApplianceParams) SetImage(image string) {
	o.Image = image
}

// WithNickname adds the nickname to the post1 appliances appliance params
func (o *Post1AppliancesApplianceParams) WithNickname(nickname string) *Post1AppliancesApplianceParams {
	o.SetNickname(nickname)
	return o
}

// SetNickname adds the nickname to the post1 appliances appliance params
func (o *Post1AppliancesApplianceParams) SetNickname(nickname string) {
	o.Nickname = nickname
}

// WriteToRequest writes these params to a swagger request
func (o *Post1AppliancesApplianceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param appliance
	if err := r.SetPathParam("appliance", o.Appliance); err != nil {
		return err
	}

	// form param image
	frImage := o.Image
	fImage := frImage
	if fImage != "" {
		if err := r.SetFormParam("image", fImage); err != nil {
			return err
		}
	}

	// form param nickname
	frNickname := o.Nickname
	fNickname := frNickname
	if fNickname != "" {
		if err := r.SetFormParam("nickname", fNickname); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
