// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPost1DevicesDeviceDeleteParams creates a new Post1DevicesDeviceDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPost1DevicesDeviceDeleteParams() *Post1DevicesDeviceDeleteParams {
	return &Post1DevicesDeviceDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPost1DevicesDeviceDeleteParamsWithTimeout creates a new Post1DevicesDeviceDeleteParams object
// with the ability to set a timeout on a request.
func NewPost1DevicesDeviceDeleteParamsWithTimeout(timeout time.Duration) *Post1DevicesDeviceDeleteParams {
	return &Post1DevicesDeviceDeleteParams{
		timeout: timeout,
	}
}

// NewPost1DevicesDeviceDeleteParamsWithContext creates a new Post1DevicesDeviceDeleteParams object
// with the ability to set a context for a request.
func NewPost1DevicesDeviceDeleteParamsWithContext(ctx context.Context) *Post1DevicesDeviceDeleteParams {
	return &Post1DevicesDeviceDeleteParams{
		Context: ctx,
	}
}

// NewPost1DevicesDeviceDeleteParamsWithHTTPClient creates a new Post1DevicesDeviceDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewPost1DevicesDeviceDeleteParamsWithHTTPClient(client *http.Client) *Post1DevicesDeviceDeleteParams {
	return &Post1DevicesDeviceDeleteParams{
		HTTPClient: client,
	}
}

/* Post1DevicesDeviceDeleteParams contains all the parameters to send to the API endpoint
   for the post1 devices device delete operation.

   Typically these are written to a http.Request.
*/
type Post1DevicesDeviceDeleteParams struct {

	/* Device.

	   Device ID.
	*/
	Device string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post1 devices device delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *Post1DevicesDeviceDeleteParams) WithDefaults() *Post1DevicesDeviceDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post1 devices device delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *Post1DevicesDeviceDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post1 devices device delete params
func (o *Post1DevicesDeviceDeleteParams) WithTimeout(timeout time.Duration) *Post1DevicesDeviceDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post1 devices device delete params
func (o *Post1DevicesDeviceDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post1 devices device delete params
func (o *Post1DevicesDeviceDeleteParams) WithContext(ctx context.Context) *Post1DevicesDeviceDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post1 devices device delete params
func (o *Post1DevicesDeviceDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post1 devices device delete params
func (o *Post1DevicesDeviceDeleteParams) WithHTTPClient(client *http.Client) *Post1DevicesDeviceDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post1 devices device delete params
func (o *Post1DevicesDeviceDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDevice adds the device to the post1 devices device delete params
func (o *Post1DevicesDeviceDeleteParams) WithDevice(device string) *Post1DevicesDeviceDeleteParams {
	o.SetDevice(device)
	return o
}

// SetDevice adds the device to the post1 devices device delete params
func (o *Post1DevicesDeviceDeleteParams) SetDevice(device string) {
	o.Device = device
}

// WriteToRequest writes these params to a swagger request
func (o *Post1DevicesDeviceDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param device
	if err := r.SetPathParam("device", o.Device); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
