// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// Post1DevicesDeviceReader is a Reader for the Post1DevicesDevice structure.
type Post1DevicesDeviceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Post1DevicesDeviceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPost1DevicesDeviceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPost1DevicesDeviceOK creates a Post1DevicesDeviceOK with default headers values
func NewPost1DevicesDeviceOK() *Post1DevicesDeviceOK {
	return &Post1DevicesDeviceOK{}
}

/* Post1DevicesDeviceOK describes a response with status code 200, with default header values.

Updated Remo
*/
type Post1DevicesDeviceOK struct {
}

// IsSuccess returns true when this post1 devices device o k response has a 2xx status code
func (o *Post1DevicesDeviceOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post1 devices device o k response has a 3xx status code
func (o *Post1DevicesDeviceOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post1 devices device o k response has a 4xx status code
func (o *Post1DevicesDeviceOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post1 devices device o k response has a 5xx status code
func (o *Post1DevicesDeviceOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post1 devices device o k response a status code equal to that given
func (o *Post1DevicesDeviceOK) IsCode(code int) bool {
	return code == 200
}

func (o *Post1DevicesDeviceOK) Error() string {
	return fmt.Sprintf("[POST /1/devices/{device}][%d] post1DevicesDeviceOK ", 200)
}

func (o *Post1DevicesDeviceOK) String() string {
	return fmt.Sprintf("[POST /1/devices/{device}][%d] post1DevicesDeviceOK ", 200)
}

func (o *Post1DevicesDeviceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
