// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// AirDirection Empty means automatic.
//
// swagger:model AirDirection
type AirDirection string

func NewAirDirection(value AirDirection) *AirDirection {
	return &value
}

// Pointer returns a pointer to a freshly-allocated AirDirection.
func (m AirDirection) Pointer() *AirDirection {
	return &m
}

const (

	// AirDirectionEmpty captures enum value ""
	AirDirectionEmpty AirDirection = ""
)

// for schema
var airDirectionEnum []interface{}

func init() {
	var res []AirDirection
	if err := json.Unmarshal([]byte(`[""]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		airDirectionEnum = append(airDirectionEnum, v)
	}
}

func (m AirDirection) validateAirDirectionEnum(path, location string, value AirDirection) error {
	if err := validate.EnumCase(path, location, value, airDirectionEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this air direction
func (m AirDirection) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateAirDirectionEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this air direction based on context it is used
func (m AirDirection) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
