// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Button button
//
// swagger:model Button
type Button struct {

	// image
	Image Image `json:"image,omitempty"`

	// Label of button.
	Label string `json:"label,omitempty"`

	// Name of button. It is used for "POST /1/{applaince}/tv" and "POST /1/{appliance}/light".
	Name string `json:"name,omitempty"`
}

// Validate validates this button
func (m *Button) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateImage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Button) validateImage(formats strfmt.Registry) error {
	if swag.IsZero(m.Image) { // not required
		return nil
	}

	if err := m.Image.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("image")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("image")
		}
		return err
	}

	return nil
}

// ContextValidate validate this button based on the context it is used
func (m *Button) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateImage(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Button) contextValidateImage(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Image.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("image")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("image")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Button) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Button) UnmarshalBinary(b []byte) error {
	var res Button
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
