// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EchonetLiteProperty The ECHONET lite properties fetched from the appliance.
// See "Detailed Requirements for ECHONET Device Objects" for more details.
// ref. https://echonet.jp/spec_object_rl_en/
//
//
// swagger:model EchonetLiteProperty
type EchonetLiteProperty struct {

	// ECHONET Property
	Epc int64 `json:"epc,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// updated at
	// Format: date-time
	UpdatedAt DateTime `json:"updated_at,omitempty"`

	// val
	Val string `json:"val,omitempty"`
}

// Validate validates this echonet lite property
func (m *EchonetLiteProperty) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateUpdatedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EchonetLiteProperty) validateUpdatedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.UpdatedAt) { // not required
		return nil
	}

	if err := m.UpdatedAt.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("updated_at")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("updated_at")
		}
		return err
	}

	return nil
}

// ContextValidate validate this echonet lite property based on the context it is used
func (m *EchonetLiteProperty) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateUpdatedAt(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EchonetLiteProperty) contextValidateUpdatedAt(ctx context.Context, formats strfmt.Registry) error {

	if err := m.UpdatedAt.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("updated_at")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("updated_at")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *EchonetLiteProperty) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EchonetLiteProperty) UnmarshalBinary(b []byte) error {
	var res EchonetLiteProperty
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
