// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SmartMeter smart meter
//
// swagger:model SmartMeter
type SmartMeter struct {

	// echonetlite properties
	EchonetliteProperties []*EchonetLiteProperty `json:"echonetlite_properties"`
}

// Validate validates this smart meter
func (m *SmartMeter) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEchonetliteProperties(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SmartMeter) validateEchonetliteProperties(formats strfmt.Registry) error {
	if swag.IsZero(m.EchonetliteProperties) { // not required
		return nil
	}

	for i := 0; i < len(m.EchonetliteProperties); i++ {
		if swag.IsZero(m.EchonetliteProperties[i]) { // not required
			continue
		}

		if m.EchonetliteProperties[i] != nil {
			if err := m.EchonetliteProperties[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("echonetlite_properties" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("echonetlite_properties" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this smart meter based on the context it is used
func (m *SmartMeter) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateEchonetliteProperties(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SmartMeter) contextValidateEchonetliteProperties(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.EchonetliteProperties); i++ {

		if m.EchonetliteProperties[i] != nil {
			if err := m.EchonetliteProperties[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("echonetlite_properties" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("echonetlite_properties" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *SmartMeter) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SmartMeter) UnmarshalBinary(b []byte) error {
	var res SmartMeter
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
